@extends('layouts.app')

@section('title', 'License Key Details')

@section('breadcrumb')
@parent
<li><a href="{{ route('license-management.index') }}">License Management</a></li>
<li><a href="{{ route('license-management.keys') }}">View Keys</a></li>
<li class="active">Key Details</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">License Key Details</h3>
                <div class="box-tools pull-right">
                    <a href="{{ route('license-management.regenerate', $licenseKey->id) }}" 
                       class="btn btn-warning btn-sm" 
                       onclick="return confirm('Are you sure you want to regenerate this key?')">
                        <i class="fa fa-refresh"></i> Regenerate
                    </a>
                    <a href="{{ route('license-management.extend', $licenseKey->id) }}" class="btn btn-success btn-sm">
                        <i class="fa fa-calendar-plus-o"></i> Extend
                    </a>
                </div>
            </div>
            <div class="box-body">
                <div class="row">
                    <div class="col-md-6">
                        <table class="table table-bordered">
                            <tr>
                                <th>Company ID</th>
                                <td>{{ $licenseKey->company_id }}</td>
                            </tr>
                            <tr>
                                <th>Company Name</th>
                                <td>{{ $licenseKey->company_name ?: 'N/A' }}</td>
                            </tr>
                            <tr>
                                <th>Issue Date</th>
                                <td>{{ $licenseKey->issue_date->format('Y-m-d') }}</td>
                            </tr>
                            <tr>
                                <th>Expiry Date</th>
                                <td>{{ $licenseKey->expiry_date->format('Y-m-d') }}</td>
                            </tr>
                            <tr>
                                <th>Duration</th>
                                <td>{{ $licenseKey->duration_days }} days</td>
                            </tr>
                            <tr>
                                <th>Status</th>
                                <td>
                                    <span class="label label-{{ $licenseKey->status == 'active' ? 'success' : 'danger' }}">
                                        {{ ucfirst($licenseKey->status) }}
                                    </span>
                                </td>
                            </tr>
                            <tr>
                                <th>Days Remaining</th>
                                <td>
                                    @if($licenseKey->daysRemaining() > 0)
                                        <span class="text-success">{{ $licenseKey->daysRemaining() }} days</span>
                                    @else
                                        <span class="text-danger">Expired {{ abs($licenseKey->daysRemaining()) }} days ago</span>
                                    @endif
                                </td>
                            </tr>
                            <tr>
                                <th>Generated By</th>
                                <td>{{ $licenseKey->generated_by }}</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label>Encrypted License Key</label>
                            <div class="input-group">
                                <textarea class="form-control" rows="4" readonly id="encrypted-key">{{ $licenseKey->license_key }}</textarea>
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" onclick="copyToClipboard('encrypted-key')">
                                        <i class="fa fa-copy"></i> Copy
                                    </button>
                                </span>
                            </div>
                        </div>
                        
                        <div class="form-group">
                            <label>Plain Text Key (Base64)</label>
                            <div class="input-group">
                                <textarea class="form-control" rows="4" readonly id="plain-key">{{ $licenseKey->plain_key }}</textarea>
                                <span class="input-group-btn">
                                    <button class="btn btn-default" type="button" onclick="copyToClipboard('plain-key')">
                                        <i class="fa fa-copy"></i> Copy
                                    </button>
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
function copyToClipboard(elementId) {
    var copyText = document.getElementById(elementId);
    copyText.select();
    copyText.setSelectionRange(0, 99999);
    document.execCommand("copy");
    
    // Show feedback
    toastr.success('Copied to clipboard!');
}
</script>
@endpush