@extends('layouts.app')

@section('title', 'View License Keys')

@section('breadcrumb')
@parent
<li><a href="{{ route('license-management.index') }}">License Management</a></li>
<li class="active">View Keys</li>
@endsection

@section('content')
<div class="row">
    <div class="col-lg-12">
        <div class="box">
            <div class="box-header with-border">
                <h3 class="box-title">License Keys</h3>
                <div class="box-tools pull-right">
                    <a href="{{ route('license-management.create') }}" class="btn btn-primary btn-sm">
                        <i class="fa fa-plus"></i> New Key
                    </a>
                    <a href="{{ route('license-management.export') }}" class="btn btn-success btn-sm">
                        <i class="fa fa-download"></i> Export CSV
                    </a>
                </div>
            </div>
            <div class="box-body table-responsive">
                <table class="table table-striped table-bordered" id="license-keys-table">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Company ID</th>
                            <th>Company Name</th>
                            <th>Issue Date</th>
                            <th>Expiry Date</th>
                            <th>Days Remaining</th>
                            <th>Status</th>
                            <th>Generated By</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>
    </div>
</div>
@endsection

@push('scripts')
<script>
$(function () {
    $('#license-keys-table').DataTable({
        processing: true,
        serverSide: true,
        ajax: '{{ route("license-management.data") }}',
        columns: [
            {data: 'id', name: 'id'},
            {data: 'company_id', name: 'company_id'},
            {data: 'company_name', name: 'company_name'},
            {data: 'issue_date', name: 'issue_date'},
            {data: 'expiry_date', name: 'expiry_date'},
            {data: 'days_remaining', name: 'days_remaining', orderable: false},
            {data: 'status', name: 'status'},
            {data: 'generated_by', name: 'generated_by'},
            {data: 'action', name: 'action', orderable: false, searchable: false}
        ]
    });
});
</script>
@endpush